/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javie
 */
public class Clientes extends javax.swing.JFrame {
        DefaultTableModel modelotabla;
        private DefaultComboBoxModel modeloCombo;
        conectar cc= new conectar();
        Connection cn= cc.conexion();
        Connection Conn;
        Statement sent;
    /**
     * Creates new form Clientes
     */
    public Clientes() {
        modelotabla = new DefaultTableModel (null, getColumnas());
        modeloCombo = new DefaultComboBoxModel(new String [] {});
        initComponents();
        cargar("");
        bloquear();
        setTitle("Clientes");
     setSize(800,560);
     setResizable(false);
     //transparente();
     setLocation(130,30);
    }
    private String [] getColumnas(){
            String columna[]= new String []{"cedula", "ruc", "nombre,","direccion","telefono"};
        return columna;
    }
    private void setFilas(){
        try {
            String sql ="select * from tcliente ";
            Statement st= cc.conexion().prepareStatement(sql);
            ResultSet rs= st.executeQuery(sql);
            
            Object datos []=new Object [5];
            while (rs.next()){
             for(int i=0; i<5; i++)  {   
                 datos [i]= rs.getObject(i+1) ;  
             } 
             modelotabla.addRow(datos);
            }
            rs.close();
             } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
}
    }
void cargar (String valor){
String[] titulos={"cedula","ruc" ,"nombre", "direccion,","telefono","foto","ruta"};
String [] registros=new String[7];
String sql="SELECT * FROM tcliente where  cedula LIKE '%" + valor + "%'";
modelotabla= new DefaultTableModel(null,titulos);
conectar cc=new conectar ();
Connection cn= cc.conexion();
try {
Statement st=cn.createStatement();
ResultSet rs= st.executeQuery(sql);
while (rs.next()){
registros[0]=rs.getString("cedula");
registros[1]=rs.getString("ruc");
registros[2]=rs.getString("nombre");
registros[3]=rs.getString("direccion");
registros[4]=rs.getString("telefono");
registros[5]=rs.getString("foto");
registros[6]=rs.getString("ruta");

modelotabla.addRow(registros);
         }
tbusuario.setModel(modelotabla);
        } catch (SQLException ex) {
JOptionPane.showMessageDialog(null,ex);
        }
}    
 void limpiar(){
     txtnom.setText("");
     txtdirec.setText("");
     txtruc.setText("");
     txtcedula.setText("");
     txtdirec.setText("");
     txttelef.setText("");
     //txttipousuario.setText("");
     //buscar.setText("");
 }
void desbloquear(){
txtnom.setEnabled(true);
txtcedula.setEnabled(true);
txtruc.setEnabled(true);
txtdirec.setEnabled(true);
txttelef.setEnabled(true);
btn_nuevo.setEnabled(false);
txtnomimagen.setEnabled(true);
//btn_eliminar.setEnabled(true);
btneditar.setEnabled(true);
btnlimpiar.setEnabled(true);
btnguardar.setEnabled(true);
btnsalir.setEnabled(true);


}
    
    void bloquear(){
txtnom.setEnabled(false);
txtcedula.setEnabled(false);
txtruc.setEnabled(false);
txtdirec.setEnabled(false);
btn_nuevo.setEnabled(true);
txttelef.setEnabled(false);
txtnomimagen.setEnabled(false);
btnguardar.setEnabled(false);
btneliminar.setEnabled(true);
btneditar.setEnabled(false);
btnlimpiar.setEnabled(false);
btnsalir.setEnabled(true);


}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbusuario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtdirec = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttelef = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_nuevo = new javax.swing.JButton();
        txtruc = new javax.swing.JTextField();
        txtnomimagen = new javax.swing.JTextField();
        aux = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tbusuario.setBackground(new java.awt.Color(153, 153, 255));
        tbusuario.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tbusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbusuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbusuario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 350, 750, 170);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRO DE CLIENTES");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 0, 320, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cédula N°");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 90, 120, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RUC N°");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 130, 80, 22);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 210, 100, 22);

        txtdirec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdirecActionPerformed(evt);
            }
        });
        getContentPane().add(txtdirec);
        txtdirec.setBounds(170, 160, 224, 30);

        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });
        getContentPane().add(txtcedula);
        txtcedula.setBounds(170, 80, 224, 30);

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        getContentPane().add(txtnom);
        txtnom.setBounds(170, 40, 224, 30);

        btnsalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Salir/salir_norm.png"))); // NOI18N
        btnsalir.setToolTipText("Salir");
        btnsalir.setBorder(null);
        btnsalir.setBorderPainted(false);
        btnsalir.setContentAreaFilled(false);
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.setFocusPainted(false);
        btnsalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Salir/salir_press.png"))); // NOI18N
        btnsalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Salir/salir_roll.png"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir);
        btnsalir.setBounds(570, 250, 103, 40);

        btnlimpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Cancelar/canc_norm.png"))); // NOI18N
        btnlimpiar.setToolTipText("Limpiar");
        btnlimpiar.setBorder(null);
        btnlimpiar.setBorderPainted(false);
        btnlimpiar.setContentAreaFilled(false);
        btnlimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlimpiar.setFocusPainted(false);
        btnlimpiar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Cancelar/canc_press.png"))); // NOI18N
        btnlimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Cancelar/canc_roll.png"))); // NOI18N
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar);
        btnlimpiar.setBounds(240, 250, 103, 35);

        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Guardar/save_norm.png"))); // NOI18N
        btnguardar.setToolTipText("Registrar");
        btnguardar.setBorder(null);
        btnguardar.setBorderPainted(false);
        btnguardar.setContentAreaFilled(false);
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar.setFocusPainted(false);
        btnguardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Guardar/save_press.png"))); // NOI18N
        btnguardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Guardar/save_roll.png"))); // NOI18N
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar);
        btnguardar.setBounds(130, 240, 103, 50);

        btneditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Editar/editar_norm.png"))); // NOI18N
        btneditar.setToolTipText("Modificar");
        btneditar.setBorder(null);
        btneditar.setBorderPainted(false);
        btneditar.setContentAreaFilled(false);
        btneditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditar.setFocusPainted(false);
        btneditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Editar/editar_press.png"))); // NOI18N
        btneditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Editar/editar_roll.png"))); // NOI18N
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        getContentPane().add(btneditar);
        btneditar.setBounds(460, 250, 103, 35);

        btneliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Eliminar/eliminar_norm.png"))); // NOI18N
        btneliminar.setToolTipText("Eliminar");
        btneliminar.setBorder(null);
        btneliminar.setContentAreaFilled(false);
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.setFocusPainted(false);
        btneliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Eliminar/eliminar_press.png"))); // NOI18N
        btneliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Eliminar/eliminar_roll.png"))); // NOI18N
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar);
        btneliminar.setBounds(350, 250, 103, 35);

        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 50, 210, 150);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dirección");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 170, 90, 22);

        txttelef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefActionPerformed(evt);
            }
        });
        getContentPane().add(txttelef);
        txttelef.setBounds(170, 200, 224, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre y Apellido:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 50, 146, 19);

        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Nuevo/nuevo_norm.png"))); // NOI18N
        btn_nuevo.setToolTipText("Nuevo");
        btn_nuevo.setBorder(null);
        btn_nuevo.setBorderPainted(false);
        btn_nuevo.setContentAreaFilled(false);
        btn_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nuevo.setFocusPainted(false);
        btn_nuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Nuevo/nuevo_press.png"))); // NOI18N
        btn_nuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones_icon/Nuevo/nuevo_roll.png"))); // NOI18N
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevo);
        btn_nuevo.setBounds(10, 250, 110, 35);

        txtruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrucActionPerformed(evt);
            }
        });
        getContentPane().add(txtruc);
        txtruc.setBounds(170, 120, 224, 30);
        getContentPane().add(txtnomimagen);
        txtnomimagen.setBounds(420, 210, 210, 30);

        aux.setBorder(null);
        aux.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                auxKeyReleased(evt);
            }
        });
        getContentPane().add(aux);
        aux.setBounds(290, 310, 210, 30);

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BUSCAR");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 310, 50, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/background-blue-grundgy-wallpapers-wallpaper-clean-miscellaneous-....jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdirecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdirecActionPerformed
        // TODO add your handling code here:
        txtdirec.transferFocus();
    }//GEN-LAST:event_txtdirecActionPerformed

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
        txtnom.transferFocus();
    }//GEN-LAST:event_txtnomActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        dispose();
        new F_Menu_P().setVisible(true);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
        txtnom.requestFocus();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
       try {
            conectar cc=new conectar();
            Connection cn= cc.conexion();
            FileInputStream archivofoto;
            String cedula,ruc, nombre, direccion, telefono,ruta;
            String sql="";
            cedula=txtcedula.getText();
            ruc=txtruc.getText();
             nombre=txtnom.getText();
            direccion=txtdirec.getText();
            telefono=txttelef.getText();
            ruta=txtnomimagen.getText();
            sql="INSERT INTO tcliente (cedula,ruc, nombre, direccion, telefono, foto,ruta)VALUES(?,?,?,?,?,?,?)";
            PreparedStatement pst=cn.prepareStatement(sql);
            pst.setString(1,cedula);
            pst.setString (2,ruc);
            pst.setString(3,nombre);
            pst.setString(4,direccion);
            pst.setString(5,telefono);
            pst.setString(6,txtnomimagen.getText());
            archivofoto= new FileInputStream(txtnomimagen.getText());
            pst.setBinaryStream(6, archivofoto);
            pst.setString(7,ruta);
            int n=pst.executeUpdate();
            if (n>0){
               cargar("");
                JOptionPane.showMessageDialog(null,"Registro");
                bloquear();
            }
        } catch (SQLException ex) {
           Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtnom.setText("");
        txtcedula.setText("");
        txtruc.setText("");
        txtdirec.setText("");
        txttelef.setText("");
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        try{
            conectar cc = new conectar();
            Connection cn = cc.conexion();
            String sql="UPDATE tcliente SET cedula=?,ruc=?, nombre=?, direccion=?, telefono=?, ruta=?,foto=?"
            +"WHERE cedula=?";
            int fila=tbusuario.getSelectedRow();
            FileInputStream archivofoto;
            String dao=(String)tbusuario.getValueAt(fila,0);
            PreparedStatement ps=cn.prepareCall(sql);
            ps.setString(1,txtcedula.getText());
            ps.setString(2,txtruc.getText());
            ps.setString(3,txtnom.getText());
            ps.setString(4,txtdirec.getText());
            ps.setString(5,txttelef.getText());
            ps.setString(6,txtnomimagen.getText());
            archivofoto= new FileInputStream(txtnomimagen.getText());
            ps.setBinaryStream(7, archivofoto);//valor de campos de texto a pasar a
            ps.setString(8,dao);//la llamada sql se muestra en la tabla
            /*Image i=null;
            Blob blob=rs.getBlob("IMAGEN");
            i=javax.imageio.ImageIO.read(blob.getBinaryStream());
            ImageIcon image=new ImageIcon(i.getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(), Image.SCALE_REPLICATE));
            jLabel7.setIcon(image);*/
            int n=ps.executeUpdate();
            if(n>0){
                limpiar();
                cargar("");
                JOptionPane.showMessageDialog(null, "Datos modificados");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "No seleccionaste nada que editar");
        }
    }//GEN-LAST:event_btneditarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        int eliminar;
        eliminar = tbusuario.getSelectedRow();
        if (eliminar == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila");
        } else {
            int valor = JOptionPane.showConfirmDialog(null, "Seguro desea eliminar?", "Advertencia", JOptionPane.YES_NO_OPTION);
            if (valor == JOptionPane.YES_OPTION) {
                int fila = tbusuario.getSelectedRow();
                String cod = "";
                cod = tbusuario.getValueAt(fila, 0).toString();
                try {
                    PreparedStatement pst = cn.prepareStatement("DELETE FROM tcliente WHERE cedula='" + cod + "'");
                    int n = pst.executeUpdate();
                    if (n > 0) {
                        JOptionPane.showMessageDialog(null, "Borrado");
                        tbusuario.setModel(new DefaultTableModel());
                        limpiar();
                        //bloquear();
                        cargar("");
                    } else {
                        JOptionPane.showMessageDialog(null, "no se borro");
                    }
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txttelefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
      desbloquear();
        txtnom.requestFocus();
        txtcedula.setText("");
        txtruc.setText("");
        txtdirec.setText("");
        txttelef.setText("");
        txtnomimagen.setText("");
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void txtrucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrucActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
   String ruta,nombre;
        final JFileChooser elegirImagen = new JFileChooser();
        elegirImagen.setMultiSelectionEnabled(false);
        int o = elegirImagen.showOpenDialog(this);
        if(o == JFileChooser.APPROVE_OPTION){
            ruta = elegirImagen.getSelectedFile().getAbsolutePath();
            nombre = elegirImagen.getSelectedFile().getName();
            txtnomimagen.setText(ruta);
            Image preview = Toolkit.getDefaultToolkit().getImage(ruta);
            if(preview != null){
                jLabel4.setText("");
                ImageIcon icon = new ImageIcon(preview.getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_DEFAULT));
                jLabel4.setIcon(icon);
            }
        }
       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void tbusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbusuarioMouseClicked
        // TODO add your handling code here:
        if(evt.getButton()==1){
            try{
                conectar cc = new conectar();
                Connection cn = cc.conexion();
                desbloquear();
                InputStream is;
                int fila=tbusuario.getSelectedRow();
                String sql="select * from tcliente where cedula="+tbusuario.getValueAt(fila,0);
                Statement sent = cn.createStatement();
                ResultSet rs=sent.executeQuery(sql);
                rs.next();
                txtcedula.setText(rs.getString("cedula"));
                txtruc.setText(rs.getString("ruc"));
                txtnom.setText(rs.getString("nombre"));
                txtdirec.setText(rs.getString("direccion"));
                txttelef.setText(rs.getString("telefono"));
                txtnomimagen.setText(rs.getString("ruta"));
               Image i=null;
                Blob blob=rs.getBlob("foto");
                i=javax.imageio.ImageIO.read(blob.getBinaryStream());
                ImageIcon image=new ImageIcon(i.getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_REPLICATE));
                jLabel4.setIcon(image);
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tbusuarioMouseClicked

    private void auxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auxKeyReleased
        // TODO add your handling code here:
        cargar(aux.getText());
    }//GEN-LAST:event_auxKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aux;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbusuario;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtdirec;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnomimagen;
    private javax.swing.JTextField txtruc;
    private javax.swing.JTextField txttelef;
    // End of variables declaration//GEN-END:variables
    
}
